DROP DATABASE IF EXISTS database_db;
CREATE DATABASE database_db;

USE database_db;

CREATE TABLE department (
    ID INT NOT NULL AUTO_INCREMENT,
    Name VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE role (
    ID INT NOT NULL AUTO_INCREMENT,
    Title VARCHAR(30) NOT NULL,
    Salary DECIMAL NOT NULL,
    Department_ID INT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE employee (
    ID INT NOT NULL AUTO_INCREMENT,
    First_Name VARCHAR(30) NOT NULL,
    Last_Name VARCHAR(30) NOT NULL,
    Role_ID INT NOT NULL,
    Manager_ID INT NULL,
    PRIMARY KEY (ID)
);

